# Copyright Korea Space Data Co., Ltd. 2020 All Rights Reserved.
version: '3.7'

services:
  app:
    container_name: app
    build: .
    environment: 
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}    
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d/
      - ./db/data/:/var/lib/mysql